services:
  php:
    image: localhost:5000/php:dev
    build: . 
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www/html
    restart: always

#  postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: myapp
#      POSTGRES_PASSWORD: superPassword
#      POSTGRES_DATABASE: myapp
#      PGDATA: /data/postgres
#    volumes:
#       - ./postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    restart: always
#  
#  redis:
#    image: redis:alpine


#    cpus: "0.5"
#    mem_reservation: "10M"
#    mem_limit: "250M"

